### ISSUE TITLE
how to extract specific key from a service and add it to Azure Key Vault

### ISSUE THREAD

**Issue by danvanderboom** [Azure-Samples/azure-cli-samples#228]
Using this script, I can list all the account keys for a Cosmos DB database:

az cosmosdb list-keys \
	--name $accountName \
	--resource-group $resourceGroupName

1. How is a specific key (like the primary account key) extracted/selected from the resulting list?
2. What Azure CLI script will insert the selected key as a new secret in an Azure Key Vault?

**Comment by danvanderboom** [comment]
Figured it out.

# get the Cosmos DB master account key
dbMasterKey="$(az cosmosdb list-keys --name $dbAccountName --resource-group $dbResourceGroup --query "primaryMasterKey" --output tsv)"

# insert master account key into Azure Key Vault
az keyvault secret set --vault-name $keyVaultName --name 'CosmosDBPassword' --value $dbMasterKey

**Comment by sdwheeler** [comment]
Closing this since you have your answer.
