### ISSUE TITLE
creating VM-IIS

### ISSUE THREAD

**Issue by SenseiJoe** [Azure-Samples/azure-cli-samples#246]
az vm extension set \
  --publisher Microsoft.Compute \
  --version 1.8 \
  --name CustomScriptExtension \
  --vm-name myVM \
  --resource-group myResourceGroup \
  --settings '{"commandToExecute":"powershell.exe Install-WindowsFeature -Name Web-Server"}'

Returns:
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by MouthOfMadness** [comment]
I got it to work by doing this:

Before:
--settings '{"commandToExecute":"powershell.exe Install-WindowsFeature -Name Web-Server"}'
After
--settings '{\"commandToExecute\":\"powershell.exe Install-WindowsFeature -Name Web-Server\"}'

**Comment by dbradish-microsoft** [comment]
@carlrab , Please and close this issue once the Azure VM scripts have been refreshed.

**Comment by carlrab** [comment]
script has been retired. If you feel that this script is important, please advise.
