### ISSUE TITLE
This repo should also allow addition of python script samples

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure-Samples/azure-cli-samples#249]
Some scripts contains logic which is hard to write in sh or bat and most probably users will also be using .py for writing such scripts.

Can we add .py scripts into this repo?

Side Query:
Once a sample .sh is added then where it can be discovered?

**Comment by dbradish-microsoft** [comment]
@gauravsaralMs , The intent of this repo is for the Azure CLI only.  For Python samples, please see [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python) repo.
