### ISSUE TITLE
Ehat is [tab][tab]

### ISSUE THREAD

**Issue by eliassal** [Azure-Samples/azure-cli-samples#301]
At https://github.com/xinity/azure-cli, there is a command as follows

`az vm show -g [tab][tab]`

what is [tab][tab]? when I run it in terminal I get

> az: error: unrecognized arguments: [tab][tab]

**Comment by dbradish-microsoft** [comment]
@eliassal, the link you provided is a fork from the [Azure/azure-cli](https://github.com/Azure/azure-cli) repo.  If this remains an issue, please post your comments in the Azure/azure-cli repo.  Thank you.
