### ISSUE TITLE
Add example of custom-data text 

### ISSUE THREAD

**Issue by asiebenwirth-ish** [Azure-Samples/azure-cli-samples#304]
Hi,

Would you add an example of adding custom-data as an inline text argument instead of file reference?

Not sure if this is correct.

`az vm create --resource-group myResourceGroup --name myVM --image UbuntuLTS --generate-ssh-keys --custom-data '#cloud-config\nhostname: myhostname'`

Refering to
https://github.com/Azure-Samples/azure-cli-samples/tree/master/virtual-machine/create-vm-customdata

Thanks!

**Comment by dbradish-microsoft** [comment]
@carlrab , Please reply and close this issue once the Azure VM scripts have been refreshed.

**Comment by carlrab** [comment]
This script has been retired. If you feel it is important to restore and improve this script, please advise.
