### ISSUE TITLE
Create Windows VM (quick) no longer available? 

### ISSUE THREAD

**Issue by bdcoder2** [Azure-Samples/azure-cli-samples#381]
A few months ago, there was an example located at:

[https://github.com/Azure-Samples/azure-cli-samples/blob/master/virtual-machine/create-vm-quick/create-windows-vm-quick.sh](https://github.com/Azure-Samples/azure-cli-samples/blob/master/virtual-machine/create-vm-quick/create-windows-vm-quick.sh)

Has that resource been permanently removed or is it located elsewhere?

Can it be restored?

Thanks in advance

**Comment by carlrab** [comment]
I am restoring it now
