### ISSUE TITLE
AFD Deploy Custom Domain sample - continuous integration

### ISSUE THREAD

**Issue by DanielLarsenNZ** [Azure-Samples/azure-cli-samples#413]
<https://github.com/Azure-Samples/azure-cli-samples/tree/master/azure-front-door/deploy-custom-domain>

As discussed, let's try building a GitHub action that will periodically test and assert:

- [ ] Scripts are re-runnable, without error, and do what they promise
- [ ] Detect breaking changes in Azure services and AZ CLI

These test assets will also be useful to users of this sample.

**Comment by DanielLarsenNZ** [comment]
@carlrab please assign to you and me :)

**Comment by dbradish-microsoft** [comment]
Closing GitHub issue as this project has been put on hold.
