### ISSUE TITLE
script doesn't run as is

### ISSUE THREAD

**Issue by flang-msft** [Azure-Samples/azure-cli-samples#481]
https://github.com/Azure-Samples/azure-cli-samples/tree/master/redis-cache

The scripts in this folder needed to checked and rerun.

1.  These don't run 'as-is"
2. Even if they ran, they would basically create a resource and delete a resource without anything being illustrated.  There are no pauses, for example, but that is hard to do when they don't run in the first place because the variables section fails.
3.  I suggest that there be a create cache/resource group script and delete cache /resource group script.

# Create a resource group
echo "Creating $resourceGroup in "$location"..."
az group create --name $resourceGroup --location "$location" --tags $tag

# shoud be:
# az group create --resourcegroup $resourceGroup --location "$location" --tags $tag
# like all the others

# Create a Basic C0 (256 MB) Redis Cache
echo "Creating $cache"
az redis create --name $cache --resource-group $resourceGroup --location "$location" --sku $sku --vm-size $size

# Get details of an Azure Cache for Redis
echo "Showing details of $cache"
az redis show --name $cache --resource-group $resourceGroup 

# Retrieve the hostname and ports for an Azure Redis Cache instance
redis=($(az redis show --name $cache --resource-group $resourceGroup --query [hostName,enableNonSslPort,port,sslPort] --output tsv))

# Retrieve the keys for an Azure Redis Cache instance
keys=($(az redis list-keys --name $cache --resource-group $resourceGroup --query [primaryKey,secondaryKey] --output tsv))

# Display the retrieved hostname, keys, and ports
echo "Hostname:" ${redis[0]}
echo "Non SSL Port:" ${redis[2]}
echo "Non SSL Port Enabled:" ${redis[1]}
echo "SSL Port:" ${redis[3]}
echo "Primary Key:" ${keys[0]}
echo "Secondary Key:" ${keys[1]}

# Delete a redis cache
echo "Deleting $cache"
az redis delete --name $resourceGroup --resource-group $resourceGroup -y

# should be
# az redis delete --name $name --resource-group $resourceGroup -y

**Comment by dbradish-microsoft** [comment]
@flang-msft , The `--name` parameter is required for [az group create](https://learn.microsoft.com/en-us/cli/azure/group#az-group-create), so I'm not seeing the issue with this part of the script.

`Delete a redis cache` however, needs an update.  This has been completed in PR [516](https://github.com/Azure-Samples/azure-cli-samples/pull/516/files).
