### ISSUE TITLE
Small typo in script with service endpoint for CosmosDB

### ISSUE THREAD

**Issue by treimers** [Azure-Samples/azure-cli-samples#482]
Hi,

thanks for theses samples here, very helpful.

I found a minor problem in this script with service endpoint for CosmosDB:

[https://github.com/Azure-Samples/azure-cli-samples/blob/master/cosmosdb/common/service-endpoints.sh](https://github.com/Azure-Samples/azure-cli-samples/blob/master/cosmosdb/common/service-endpoints.sh)

The line with 'Variable block' is missing a leading '#'. It should read

#Variable block

**Comment by dbradish-microsoft** [comment]
Thank you @treimers, for bringing this to our attention. This has been corrected.
