### ISSUE TITLE
Incorrect steps provided for "Azure CLI: Bind a custom TLS/SSL certificate to a web app"

### ISSUE THREAD

**Issue by sth2258** [Azure-Samples/azure-cli-samples#510]
Page "https://github.com/Azure-Samples/azure-cli-samples/blob/master/app-service/configure-ssl-certificate/configure-ssl-certificate-webapp-only.sh" is linked directly from "https://learn.microsoft.com/en-us/azure/app-service/configure-ssl-certificate?tabs=apex#how-can-i-automate-adding-a-bring-your-owncertificate-to-an-app" in the instructions sections for "Azure CLI: Bind a custom TLS/SSL certificate to a web app"

configure-ssl-certificate-webapp-only.sh does not provision the webapp as described, and seems to link to a page (app-service/scripts/cli-configure-ssl-certificate.md) which also doesn't appear to exist.

**Comment by sujitks** [comment]
@sth2258 is right, the sample script provided is only for creating a web app using the cli and nothing to do with custom dns binding.

**Comment by dbradish-microsoft** [comment]
@msangapu-msft, Please respond to this GitHub issue.  Thank you.

**Comment by dbradish-microsoft** [comment]
@sth2258  & @msangapu-msft , I've moved this GitHub issue to azure-docs issue #[121657](https://github.com/MicrosoftDocs/azure-docs/issues/121657) as the change needs to originate from the conceptual content.

**Comment by AjayKumar-MSFT** [comment]
This doc provide the (following) steps: 
https://github.com/Azure-Samples/azure-cli-samples/blob/master/app-service/configure-ssl-certificate/configure-ssl-certificate.sh


<img width="299" alt="image" src="https://github.com/Azure-Samples/azure-cli-samples/assets/44606227/3b57b29a-dd7d-4211-a4b8-187709cf2ae3">





The linked page at [configure-ssl-certificate-webapp-only.sh](https://github.com/Azure-Samples/azure-cli-samples/blob/master/app-service/configure-ssl-certificate/configure-ssl-certificate-webapp-only.sh), , at 42 points to this URL which works: [configure-ssl-certificate/configure-ssl-certificate.sh]( https://github.com/Azure-Samples/azure-cli-samples/blob/master/app-service/configure-ssl-certificate/configure-ssl-certificate.sh)


#!/bin/bash

fqdn=<replace-with-www.{yourdomain}>
pfxPath=<replace-with-path-to-your-.PFX-file>
pfxPassword=<replace-with-your=.PFX-password>
resourceGroup=myResourceGroup
webappname=mywebapp$RANDOM

**#Create a resource group.**
az group create --location westeurope --name $resourceGroup

**#Create an App Service plan in Basic tier (minimum required by custom domains).**
az appservice plan create --name $webappname --resource-group $resourceGroup --sku B1

**#Create a web app.**
az webapp create --name $webappname --resource-group $resourceGroup \
--plan $webappname

echo "Configure a CNAME record that maps $fqdn to $webappname.azurewebsites.net"
read -p "Press [Enter] key when ready ..."

#Before continuing, go to your DNS configuration UI for your custom domain and follow the 
#instructions at https://aka.ms/appservicecustomdns to configure a CNAME record for the 
#hostname "www" and point it your web app's default domain name.

**#Map your prepared custom domain name to the web app.**
az webapp config hostname add --webapp-name $webappname --resource-group $resourceGroup \
--hostname $fqdn

**#Upload the SSL certificate and get the thumbprint.**
thumbprint=$(az webapp config ssl upload --certificate-file $pfxPath \
--certificate-password $pfxPassword --name $webappname --resource-group $resourceGroup \
--query thumbprint --output tsv)

**#Binds the uploaded SSL certificate to the web app.**
az webapp config ssl bind --certificate-thumbprint $thumbprint --ssl-type SNI \
--name $webappname --resource-group $resourceGroup

echo "You can now browse to https://$fqdn"
